### ISSUE TITLE
The container does not start itself with the host boot-up

### ISSUE THREAD

**Issue by yrcs** [dragonflyoss/image-service#691]
```Shell
nerdctl --snapshotter nydus pull yrcs/an8-nydus-mariadb:10.6.9
nerdctl --snapshotter nydus run --name mariadb -d --restart always -p 3306:3306 -e MARIADB_ROOT_PASSWORD=123456 -v /srv/mariadb/datadir:/var/lib/mysql yrcs/an8-nydus-mariadb:10.6.9
```
`reboot` the host machine. Then enter the following command:
```Shell
nerdctl logs -n 10 mariadb
# The following error message is displayed.
FATA[0000] no running task found: task b48af7d4e05d7bec6b025270440bbb6658cb28c10a9f9355b9a1053ee99ad330 not found: not found.
# Then enter the following command to start the container:
nerdctl start mariadb
# The following error message is displayed.
FATA[0000] file does not exist: unknown
# But the container actually exists. Enter the following command to verify:
nerdctl ps -a
# The results are shown below.
CONTAINER ID    IMAGE                                      COMMAND                   CREATED           STATUS     PORTS                     NAMES
b48af7d4e05d    docker.io/yrcs/an8-nydus-mariadb:10.6.9    "docker-entrypoint.s…"    26 minutes ago    Created    0.0.0.0:3306->3306/tcp    mariadb
```
So, why did it report: "**FATA[0000] file does not exist: unknown**" ?
The **nydus-snapshotter.service** is as follows:
```Shell
[Unit]
Description=nydus snapshotter
After=network.target
Before=containerd.service

[Service]
Type=simple
Environment=HOME=/root
ExecStart=/usr/bin/containerd-nydus-grpc \
    --config-path /etc/nydus/nydusd-config.json \
    --shared-daemon \
    --log-level info \
    --root /var/lib/containerd/io.containerd.snapshotter.v1.nydus \
    --cache-dir /var/lib/nydus/cache \
    --address /run/containerd/containerd-nydus-grpc.sock \
    --nydusd-path /usr/bin/nydusd \
    --nydusimg-path /usr/bin/nydus-image
Restart=always
RestartSec=1
KillMode=process
OOMScoreAdjust=-999
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
```

**Comment by changweige** [comment]
My working VM can't be restarted. Can you please share the nydusd.log and nydus-snapshotter.log ?

**Comment by yrcs** [comment]
> My working VM can't be restarted. Can you please share the nydusd.log and nydus-snapshotter.log ?

There is no "**nydusd.log**" as you mentioned on my machine. Only the **nydus-snapshotter.log** is as follows:
```Shell
Aug 23 10:20:13 localhost.localdomain containerd-nydus-grpc[835]: time="2022-08-23T10:20:13.262529200+08:00" level=info msg="id 18 is data layer, continue to check parent layer"
Aug 23 10:20:13 localhost.localdomain containerd-nydus-grpc[835]: time="2022-08-23T10:20:13.263353859+08:00" level=error msg="snapshot 6 is not ready, err: file does not exist"
```
And there is also with an occasional problem occurs when running the container for the first time, but when run again the problem disappears.
```Shell
FATA[0001] failed to wait shared daemon: wait until daemon ready by checking status: failed to do HTTP GET from http://unix/api/v1/daemon: Get "http://unix/api/v1/daemon": dial unix /var/lib/containerd/io.containerd.snapshotter.v1.nydus/socket/shared_daemon/api.sock: connect: connection refused: unknown
```

**Comment by changweige** [comment]
Yes. I can reproduce this problem.  I am going to delve into this issue. Hopefully, I can fix it in the soon future. Thanks for reporting. I will duplicate this ISSUE into nydus-snapshotter's repo since it is its flaw.

**Comment by changweige** [comment]
This PR should fix the problem you reported https://github.com/containerd/nydus-snapshotter/pull/145

**Comment by yrcs** [comment]
> This PR should fix the problem you reported [containerd/nydus-snapshotter#145](https://github.com/containerd/nydus-snapshotter/pull/145)

I don't think so. The root cause is a programming design problem (no one wants to manually start a new **nydusd** on every boot-up to solve this problem). So, this bug remains unresolved.

**Comment by changweige** [comment]
> > This PR should fix the problem you reported [containerd/nydus-snapshotter#145](https://github.com/containerd/nydus-snapshotter/pull/145)
> 
> I don't think so. The root cause is a programming design problem (no one wants to manually start a new **nydusd** on every boot-up to solve this problem). So, this bug remains unresolved.

True. I have to admit that nydus-snapshotter is not user-friendly enough. We are working on improving its usability including 
easy installation setup, snapshotter's configuration file and robust `nydusd` daemon status management. Hope it will be much easier to be deployed in the production environment.

**Comment by changweige** [comment]
This should be fixed by recent nydus-snapshotter improvements. Can we close it?

**Comment by yrcs** [comment]
> This should be fixed by recent nydus-snapshotter improvements. Can we close it?

OK! Just close it.
